(function(){
'use strict';
var API=(window.PERSPECTIVES_API_URL||'https://perspectives-emploi-api-production.up.railway.app').replace(/\/$/,'');
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
var STOP={avec:1,dans:1,pour:1,sans:1,sous:1,vers:1,chez:1,cette:1,comme:1,plus:1,moins:1,tout:1,tous:1,toute:1,toutes:1,vous:1,nous:1,votre:1,vos:1,notre:1,nos:1,leur:1,leurs:1,une:1,des:1,les:1,aux:1,sur:1,par:1,que:1,qui:1,est:1,sont:1,etre:1,avoir:1,faire:1,mise:1,mettre:1,service:1,services:1,emploi:1,emplois:1,travail:1,travaux:1,gestion:1,suivi:1,accompagnement:1,experience:1,experiences:1,professionnel:1,professionnelle:1};
function tok(s){var a=norm(s).split(' '),out=[];a.forEach(function(w){if(w.length>=4&&!STOP[w]&&out.indexOf(w)<0)out.push(w)});return out}
function readCV(){try{return JSON.parse(sessionStorage.getItem('perspectives_cv_analysis')||'null')}catch(e){return null}}
function flatten(o,out){out=out||[];if(o==null)return out;if(typeof o==='string')out.push(o);else if(Array.isArray(o))o.forEach(function(x){flatten(x,out)});else if(typeof o==='object')Object.keys(o).forEach(function(k){if(!/mail|phone|telephone|adresse|address|nom|prenom/i.test(k))flatten(o[k],out)});return out}
function evidence(cv){var skills=(cv&&Array.isArray(cv.competences_cv)?cv.competences_cv:[]).map(String),all=flatten(cv||{}).map(String).filter(function(x){return x.length>2});skills.forEach(function(x){if(all.indexOf(x)<0)all.push(x)});return {skills:skills,all:all}}
function overlap(a,b){var A=tok(a),B=tok(b);if(!A.length||!B.length)return 0;var c=0;A.forEach(function(x){if(B.indexOf(x)>=0)c++});return c/Math.max(1,Math.min(A.length,B.length))}
function best(label,all){var score=0,proof='';all.forEach(function(e){var s=overlap(label,e);if(s>score){score=s;proof=e}});return {score:score,proof:proof}}
async function getJSON(url){try{var r=await fetch(url);if(!r.ok)return null;return await r.json()}catch(e){return null}}
async function searchJobs(q){var d=await getJSON(API+'/api/rome/metiers?q='+encodeURIComponent(q));return Array.isArray(d)?d:[]}
async function getSkills(code){var d=await getJSON(API+'/api/rome/competences?code_rome='+encodeURIComponent(code));return d&&Array.isArray(d.competences)?d.competences:[]}
function titleMatch(job,all){var label=norm(job.libelle),score=0,proof='';all.forEach(function(e){var n=norm(e),s=overlap(label,n);if(label.indexOf('insertion professionnelle')>=0&&/(conseiller.*insertion|cip|insertion professionnelle)/.test(n))s=Math.max(s,.98);if(s>score){score=s;proof=e}});return {score:score,proof:proof}}
async function candidates(ev){var map={},queries=[];ev.all.forEach(function(e){var n=norm(e);if(/conseiller|charge|formateur|animateur|assistant|responsable|agent|technicien|vendeur|conducteur|developpeur|insertion|recrutement|orientation/.test(n)){var q=tok(e).slice(0,6).join(' ');if(q.length>4&&queries.indexOf(q)<0)queries.push(q)}});if(ev.all.some(function(e){return /(conseiller.*insertion|cip|insertion professionnelle|accompagnement.*emploi)/i.test(e)}))queries.unshift('conseiller insertion professionnelle');var skillWords=[];ev.skills.forEach(function(e){tok(e).slice(0,2).forEach(function(w){if(skillWords.indexOf(w)<0)skillWords.push(w)})});queries=queries.slice(0,8).concat(skillWords.slice(0,10));for(var i=0;i<queries.length;i++){var list=await searchJobs(queries[i]);list.forEach(function(j){map[(j.code||'')+'|'+j.libelle]=j})}return Object.keys(map).map(function(k){return map[k]}).slice(0,40)}
async function evaluate(job,ev){var skills=await getSkills(job.code);if(!skills.length)return null;var tm=titleMatch(job,ev.all),strong=0,partial=0,matched=[];skills.forEach(function(s){var m=best(s.libelle,ev.all);if(m.score>=.58){strong++;matched.push({label:s.libelle,partial:false})}else if(m.score>=.32){partial++;matched.push({label:s.libelle,partial:true})}});var evidenceLevel=Math.min(1,(strong*3+partial*1.25)/24),titleLevel=tm.score>=.8?1:(tm.score>=.55?.72:(tm.score>=.35?.4:0)),confidence=Math.min(1,titleLevel*.62+evidenceLevel*.38),level='À explorer';if((titleLevel>=.72&&evidenceLevel>=.22)||confidence>=.68)level='Très forte correspondance';else if(confidence>=.43||strong>=6)level='Forte correspondance';return {code:job.code,libelle:job.libelle,level:level,confidence:confidence,titleScore:tm.score,strong:strong,partial:partial,matched:matched.slice(0,4)}}
async function suggest(){var cv=readCV(),ev=evidence(cv);if(!ev.all.length)return {direct:[],develop:[],note:'Aucun élément exploitable détecté dans le CV.'};var jobs=await candidates(ev),out=[];for(var i=0;i<Math.min(jobs.length,24);i++){var x=await evaluate(jobs[i],ev);if(x&&(x.titleScore>=.28||x.strong>=2||x.partial>=3))out.push(x)}out.sort(function(a,b){return b.confidence-a.confidence||b.titleScore-a.titleScore||b.strong-a.strong});var seen={},clean=[];out.forEach(function(x){var k=norm(x.libelle);if(!seen[k]){seen[k]=1;clean.push(x)}});return {direct:clean.filter(function(x){return x.level!=='À explorer'}).slice(0,6),develop:clean.filter(function(x){return x.level==='À explorer'}).slice(0,6),note:'Classement indicatif fondé d’abord sur les métiers et expériences du CV, puis sur les compétences ROME et les compétences transférables.'}}
function card(j){var why=[];if(j.titleScore>=.55)why.push('Métier ou activité proche repéré dans le CV');if(j.strong)why.push(j.strong+' compétence'+(j.strong>1?'s':'')+' ROME fortement retrouvée'+(j.strong>1?'s':''));if(j.partial)why.push(j.partial+' élément'+(j.partial>1?'s':'')+' à confirmer');return '<article class="compatible-card"><div class="compatible-card-top"><div><h5>'+esc(j.libelle)+'</h5><span>ROME '+esc(j.code||'—')+'</span></div><b class="compatible-level">'+esc(j.level)+'</b></div><ul class="compatible-reasons">'+why.map(function(x){return '<li>'+esc(x)+'</li>'}).join('')+'</ul><button class="compatible-select" type="button" data-code="'+esc(j.code||'')+'" data-label="'+esc(j.libelle||'')+'">Comparer ce métier avec mon CV →</button></article>'}
function addStyles(){if(document.getElementById('compatibleJobsStyles'))return;var s=document.createElement('style');s.id='compatibleJobsStyles';s.textContent='.compatible-head h3{color:#17236b;font-size:22px;margin:0 0 8px}.compatible-head p{color:#6f7690}.compatible-section-title{color:#17236b;margin:24px 0 12px}.compatible-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.compatible-card{border:1px solid #dfe3f2;border-radius:14px;background:#fff;padding:18px}.compatible-card-top{display:flex;justify-content:space-between;gap:12px}.compatible-card h5{font-size:16px;margin:0 0 4px}.compatible-card span{font-size:12px;color:#727991}.compatible-level{background:#eaf0ff;color:#263987;border-radius:16px;padding:7px 10px;font-size:12px;height:max-content}.compatible-reasons{padding-left:18px;font-size:13px}.compatible-select{width:100%;border:0;border-radius:9px;background:#2d3987;color:#fff;padding:11px;font-weight:700}.compatible-empty{padding:18px;border:1px dashed #cbd1e6;border-radius:12px;color:#737a91}@media(max-width:900px){.compatible-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
async function render(host){addStyles();host.innerHTML='<div class="rome-loading">Analyse des expériences et compétences du CV avec le référentiel ROME…</div>';try{var r=await suggest();host.innerHTML='<div class="compatible-head"><h3>Métiers compatibles avec votre CV</h3><p>'+esc(r.note)+'</p></div><h4 class="compatible-section-title">Correspondances les plus solides</h4><div class="compatible-grid">'+(r.direct.length?r.direct.map(card).join(''):'<div class="compatible-empty">Aucune correspondance suffisamment solide pour le moment.</div>')+'</div><h4 class="compatible-section-title">Autres pistes à explorer</h4><div class="compatible-grid">'+(r.develop.length?r.develop.map(card).join(''):'<div class="compatible-empty">Aucune autre piste suffisamment étayée.</div>')+'</div>';Array.prototype.forEach.call(host.querySelectorAll('.compatible-select'),function(b){b.onclick=function(){sessionStorage.setItem('perspectives_target_job',JSON.stringify({code:b.dataset.code,libelle:b.dataset.label}));if(typeof window.openSkillsView==='function')window.openSkillsView();else location.reload()}})}catch(e){console.error('Compatible jobs:',e);host.innerHTML='<div class="compatible-empty">Le calcul des métiers compatibles a rencontré une erreur. Rechargez la page puis réessayez.</div>'}}
window.PerspectivesCompatibleJobs={suggest:suggest,render:render};
})();