/* Perspectives Emploi — Skills UX V2 */
(function(){
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=k=>{try{return JSON.parse(sessionStorage.getItem(k)||'null')}catch(e){return null}};
function inject(){if(document.getElementById('skillsV2Style'))return;const s=document.createElement('style');s.id='skillsV2Style';s.textContent=`.skills-v2-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.skills-v2-actions button{border:1px solid #ccd2e8;background:#fff;color:#24317d;border-radius:9px;padding:8px 11px;font-weight:700;cursor:pointer}.skills-v2-actions button.active{background:#283684;color:#fff}.skills-priority{margin:16px 0;padding:14px;border-radius:14px;background:#f7f8fd;border:1px solid #dfe3f2}.skills-priority h3{margin:0 0 5px;color:#1d2a78}.skills-priority p{margin:0;color:#68708b}.skill-row.priority{border-left:4px solid #2d3987}.skill-row.acquire{border-left:4px solid #d29b2c}.near-jobs-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.near-job{border:1px solid #dfe3f2;border-radius:12px;background:#fff;padding:13px;text-align:left;cursor:pointer}.near-job strong{display:block;color:#17236b}.near-job span{font-size:12px;color:#727991}@media(max-width:800px){.near-jobs-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function classifyType(item){const t=String(item.type||'').toLowerCase();if(t.includes('savoir_etre')||t.includes('savoir-être')||t.includes('soft'))return 'soft';if(t.includes('savoir')&&!t.includes('faire'))return 'knowledge';return 'knowhow'}
function addReturnButton(){const target=document.getElementById('skillsTarget');if(!target||document.getElementById('backCompatibleJobs'))return;const b=document.createElement('button');b.id='backCompatibleJobs';b.type='button';b.textContent='← Revenir aux métiers proposés';b.style.cssText='margin-left:auto;border:1px solid #ccd2e8;background:#fff;color:#24317d;border-radius:9px;padding:8px 11px;font-weight:700;cursor:pointer';b.onclick=()=>{sessionStorage.removeItem('perspectives_target_job');if(window.openCompatibleJobsView)window.openCompatibleJobsView()};target.appendChild(b)}
function enhanceRows(){const rows=[...document.querySelectorAll('#skillsList .skill-row')];if(!rows.length)return;rows.forEach(r=>{const type=classifyType({type:r.dataset.skillType});r.dataset.v2type=type});const checks=rows.filter(r=>r.dataset.skillState==='check'),mids=rows.filter(r=>r.dataset.skillState==='mid'),asks=rows.filter(r=>r.dataset.skillState==='ask');checks.slice(0,8).forEach(r=>r.classList.add('priority'));mids.slice(0,6).forEach(r=>r.classList.add('priority'));asks.slice(0,6).forEach(r=>r.classList.add('acquire'));const list=document.getElementById('skillsList');if(!document.getElementById('skillsPriorityIntro'))list.insertAdjacentHTML('beforebegin','<div id="skillsPriorityIntro" class="skills-priority"><h3>Compétences prioritaires</h3><p>En priorité : compétences identifiées dans le CV, éléments à confirmer avec le candidat, puis une courte sélection des compétences importantes à acquérir.</p></div>')}
function wireTabs(){document.querySelectorAll('[data-skills-tab]').forEach(btn=>{btn.onclick=async()=>{document.querySelectorAll('[data-skills-tab]').forEach(x=>x.classList.toggle('active',x===btn));const tab=btn.dataset.skillsTab;if(tab==='nearby'){await renderNearJobs();return}document.getElementById('skillsList').hidden=false;document.getElementById('skillsEmpty').hidden=true;const rows=[...document.querySelectorAll('#skillsList .skill-row')];rows.forEach(r=>r.hidden=tab!=='overview'&&r.dataset.v2type!==({knowhow:'knowhow',knowledge:'knowledge',softskills:'soft'}[tab]||tab));}})}
function wireFilters(){document.querySelectorAll('[data-skill-filter]').forEach(btn=>{btn.onclick=()=>{document.querySelectorAll('[data-skill-filter]').forEach(x=>x.classList.toggle('active',x===btn));const f=btn.dataset.skillFilter;document.querySelectorAll('#skillsList .skill-row').forEach(r=>r.hidden=f!=='all'&&r.dataset.skillState!==f)}})}
async function renderNearJobs(){const list=document.getElementById('skillsList');list.hidden=false;const job=read('perspectives_target_job');const cv=read('perspectives_cv_analysis');list.innerHTML='<div class="rome-loading">Recherche de métiers proches…</div>';if(!cv||!window.PerspectivesCompatibleJobs){list.innerHTML='<div class="rome-loading">Aucune suggestion disponible.</div>';return}try{const r=await window.PerspectivesCompatibleJobs.suggest();const jobs=[...(r.direct||[]),...(r.develop||[])].filter(x=>!job||x.code!==job.code).slice(0,8);list.innerHTML=jobs.length?'<div class="near-jobs-grid">'+jobs.map(j=>`<button class="near-job" data-code="${esc(j.code)}" data-label="${esc(j.libelle)}"><strong>${esc(j.libelle)}</strong><span>ROME ${esc(j.code)} · proximité indicative ${j.score}%</span></button>`).join('')+'</div>':'<div class="rome-loading">Aucun autre métier suffisamment proche trouvé.</div>';list.querySelectorAll('.near-job').forEach(b=>b.onclick=()=>{sessionStorage.setItem('perspectives_target_job',JSON.stringify({code:b.dataset.code,libelle:b.dataset.label}));window.openSkillsView&&window.openSkillsView()})}catch(e){list.innerHTML='<div class="rome-loading">Métiers proches momentanément indisponibles.</div>'}}
function improveScore(){const job=read('perspectives_target_job'),cv=read('perspectives_cv_analysis');if(!job||!cv)return;const title=String(job.libelle||'').toLowerCase();const text=JSON.stringify(cv).toLowerCase();let bonus=0;title.split(/\W+/).filter(w=>w.length>5).forEach(w=>{if(text.includes(w))bonus+=8});if(/insertion professionnelle/.test(title)&&/(insertion|emploi|accompagnement|conseiller|cip)/.test(text))bonus+=25;const target=document.getElementById('skillsTarget');if(target&&bonus){const badge=document.createElement('span');badge.textContent='Profil métier repéré dans le CV';badge.style.cssText='margin-left:8px;background:#e8f6ed;color:#18713c;border-radius:20px;padding:5px 9px;font-size:12px;font-weight:700';target.appendChild(badge)}}
function run(){inject();if(document.getElementById('skillsView')?.hidden)return;setTimeout(()=>{addReturnButton();enhanceRows();wireTabs();wireFilters();improveScore()},500)}
document.addEventListener('click',e=>{if(e.target.closest('.sidebar a[href="#competences"],[data-view="skills"],#skillsTabs,[data-skill-filter]'))setTimeout(run,700)},true);const obs=new MutationObserver(()=>{if(!document.getElementById('skillsView')?.hidden)run()});const v=document.getElementById('skillsView');if(v)obs.observe(v,{attributes:true,attributeFilter:['hidden']});window.PerspectivesSkillsV2={run,renderNearJobs};
})();